"""
Infrastructure – Ollama LLM adapter with streaming support.
"""
from __future__ import annotations

import logging
from typing import Generator

logger = logging.getLogger(__name__)


class OllamaLLM:
    """Chat-completions via local Ollama — supports both blocking and streaming."""

    def __init__(
        self,
        model: str = "llama3",
        base_url: str = "http://localhost:11434",
        temperature: float = 0.15,   # lower = more factual
        num_ctx: int = 4096,         # context window
    ):
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.temperature = temperature
        self.num_ctx = num_ctx

    def generate(self, prompt: str) -> str:
        import httpx
        payload = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": self.temperature,
                "num_ctx": self.num_ctx,
                "stop": ["## Question", "---\n## Question"],  # prevent hallucinating next question
            },
        }
        response = httpx.post(
            f"{self.base_url}/api/generate",
            json=payload,
            timeout=180,
        )
        response.raise_for_status()
        return response.json().get("response", "").strip()

    def stream(self, prompt: str) -> Generator[str, None, None]:
        """Yield tokens as they are generated by Ollama."""
        import httpx, json as _json
        payload = {
            "model": self.model,
            "prompt": prompt,
            "stream": True,
            "options": {
                "temperature": self.temperature,
                "num_ctx": self.num_ctx,
                "stop": ["## Question"],
            },
        }
        with httpx.stream(
            "POST",
            f"{self.base_url}/api/generate",
            json=payload,
            timeout=180,
        ) as response:
            response.raise_for_status()
            for line in response.iter_lines():
                if not line:
                    continue
                try:
                    chunk = _json.loads(line)
                    token = chunk.get("response", "")
                    if token:
                        yield token
                    if chunk.get("done"):
                        break
                except _json.JSONDecodeError:
                    continue


class MockLLM:
    """Deterministic mock for unit/integration tests."""

    def __init__(self, response: str = "MOCK_ANSWER"):
        self._response = response

    def generate(self, prompt: str) -> str:
        return self._response

    def stream(self, prompt: str) -> Generator[str, None, None]:
        for word in self._response.split():
            yield word + " "
